name: Run Concert Finder Daily

on:
  schedule:
    - cron: '2 8 * * *'  # Runs at 8:02 AM UTC = 3:00 AM Chicago time
  workflow_dispatch:  # Allows manual run
    inputs: {}

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install spotipy requests beautifulsoup4 pandas pytz

      - name: Run main.py
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
        run: |
          python main.py