name: Create Tomorrow's Playlist
on:
  schedule:
    - cron: '11 8 * * *'    # 8:11 AM UTC = 3:11 AM Chicago time
  workflow_dispatch:       # Allows manual run from GitHub
    inputs: {}
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install spotipy requests beautifulsoup4 pandas pytz
      - name: Run main.py for Tomorrow (Day 1)
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
          DAYS_IN_FUTURE: 1
        run: |
          python main.py